import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navbar/NavBar';
import { Comfortaa } from 'next/font/google';

const comfortaa = Comfortaa({
  weight: ['300', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={comfortaa.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
